Temporary fix scipy complain about imresize
Scipy now throws this error
`AttributeError: module 'scipy.misc' has no attribute 'imresize'`
due to the deprecation of imresize in scipy in >1.1.0
Installing scipy version 1.1.0 fixes this problem.

Although a more thorough code inspection might be needed to fix this problem to work with the newest version.